POST https://localhost:5001/account/login
Content-Type: application/json

{

  "email": "testing2@yahoo.com",
  "password": ""
}

###

GET https://localhost:5001/account/users
Accept: application/json

###

POST https://localhost:5001/account
Content-Type: application/json

{

  "email": "testingbb4@yahoo.com",
  "password": ""
}

###

DELETE  https://localhost:5001/account/testingb4@yahoo.com
Accept: application/json

###

PUT https://localhost:5001/account
Content-Type: application/json

{

  "email": "testing44@yahoo.com",
  "password": ""
}
###