GET https://localhost:5001/artworks/getall
Accept: application/json

###

GET https://localhost:5001/artworks/getone/22
Accept: application/json

###

GET https://localhost:5001/artworks/getallbyroom/A1
Accept: application/json

###

POST https://localhost:5001/artworks/createartwork
Content-Type: application/json

{
  "name": "Object 4 for testing",
  "description": "Object 1 for testing",
  "image": "Object 1 for testing",
  "type": "Drawing",
  "author": "Unknown",
  "location": "Storage",
  "minLight": 3,
  "maxLight": 50,
  "minCo2": 11,
  "maxCo2": 51,
  "minTemperature": 10,
  "maxTemperature": 25,
  "minHumidity": 20,
  "maxHumidity": 60,
  "artworkPosition": 1,
  "comment": "Testing purposes"
}
###

// other available artwork objects for testing: 136 and 137 ids 
//change Description of artwork object 135
PUT https://localhost:5001/artworks/edit/135
Content-Type: application/json



{ "id": 135,
  "name": "Object 1 for testing",
  "description": "Testing edit for Description on artwork object id 135 ",
  "image": "This has been changed",
  "type": "Drawing",
  "author": "Unknown",
  "location": "Storage",
  "minLight": 3,
  "maxLight": 50,
  "minCo2": 11,
  "maxCo2": 51,
  "minTemperature": 10,
  "maxTemperature": 25,
  "minHumidity": 20,
  "maxHumidity": 60,
  "artworkPosition": 1,
  "comment": "Testing purposes"
}
###

// Testing can be performed with artwork Id 135, 136, 137 
PUT https://localhost:5001/moveartwork?id=135&location=A1
Content-Type: application/json

###

DELETE https://localhost:5001/artworks/delete/138
Accept: application/json