
GET https://localhost:5001/measurements/1
Accept: application/json

###

GET https://localhost:5001/measurements
Accept: application/json

###

GET https://localhost:5001/measurements/getall/A1
Accept: application/json

###