GET https://localhost:5001/rooms/getall
Accept: application/json

###

GET https://localhost:5001/rooms/get/A1
Accept: application/json

###

GET https://localhost:5001/rooms/getdetails/A1
Accept: application/json

###

GET https://localhost:5001/rooms/getmeasurementconditions/2
Accept: application/json



###

PUT https://localhost:5001/rooms/put/A1
Content-Type: application/json

{
  "locationCode": "A1",
  "description": "Changed for testing purposes ",
  "currentCapacity": 97,
  "totalCapacity": 200,
  "light": 15,
  "temperature": 25,
  "humidity": 35,
  "co2": 10,
  "artworkList": null,
  "measurements": null
}

###


POST https://localhost:5001/rooms/createroom
Content-Type: application/json

{
  "locationCode": "A009",
  "description": "Changed for testing purposes ",
  "currentCapacity": 97,
  "totalCapacity": 200,
  "light": 15,
  "temperature": 25,
  "humidity": 35,
  "co2": 10,
  "artworkList": null,
  "measurements": null
}

###


DELETE https://localhost:5001/rooms/delete/A008
Content-Type: application/json
