// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Database;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MuseumContext))]
    partial class MuseumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.3.20181.2");

            modelBuilder.Entity("WebApplication1.Datamodel.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCo2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHumidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCo2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHumidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomLocationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomLocationCode");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Museum");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.Room", b =>
                {
                    b.Property<string>("LocationCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Co2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Light")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LiveRoomMeasurementsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationCode");

                    b.HasIndex("LiveRoomMeasurementsId");

                    b.HasIndex("MuseumId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.RoomMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Co2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Light")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RoomMeasurements");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.Administrator", b =>
                {
                    b.HasOne("WebApplication1.Datamodel.Museum", null)
                        .WithMany("AdminList")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.Artwork", b =>
                {
                    b.HasOne("WebApplication1.Datamodel.Room", null)
                        .WithMany("ArtworkList")
                        .HasForeignKey("RoomLocationCode");
                });

            modelBuilder.Entity("WebApplication1.Datamodel.Room", b =>
                {
                    b.HasOne("WebApplication1.Datamodel.RoomMeasurement", "LiveRoomMeasurements")
                        .WithMany()
                        .HasForeignKey("LiveRoomMeasurementsId");

                    b.HasOne("WebApplication1.Datamodel.Museum", null)
                        .WithMany("RoomList")
                        .HasForeignKey("MuseumId");
                });
#pragma warning restore 612, 618
        }
    }
}
